version: '3.9'

services:
  atcoder:
    build:
      context: .
      dockerfile: .devcontainer/Dockerfile  
    tty: true
    volumes:
      - type: bind
        source: .
        target: /code
      - type: bind
        source: .cache
        target: /root/.cache
      - type: bind
        source: .config
        target: /root/.config
    ports:
      - "1234:1234"
