version: '3.9'

services:
  atcoder:
    build:
      context: .
      dockerfile: .devcontainer/Dockerfile  # Dockerfileが.devcontainer内にある場合
    tty: true
    volumes:
      - type: bind
        source: .
        target: /code
      - type: bind
        source: .cache
        target: /root/.cache
      - type: bind
        source: .config
        target: /root/.config
    ports:
      - "8000:8000"
